postgresql:
  enabled: true # TEST ONLY

minio:
  enabled: true # TEST ONLY

tracking:
  ingress:
    enabled: false
    hostname: mlflow.${domain}
    ingressClassName: nginx
  service:
    type: ClusterIP
  auth:
    enabled: false # TEST ONLY

#  resources:
#    requests:
#      cpu: 200m
#      memory: 600Mi
#    limits:
#      cpu: 300m
#      memory: 600Mi
#
#run:
#  resources:
#    requests:
#      cpu: 200m
#      memory: 500Mi
#    limits:
#      cpu: 300m
#      memory: 600Mi
#
#minio:
#  resources:
#    requests:
#      cpu: 100m
#      memory: 200Mi
#    limits:
#      cpu: 150m
#      memory: 300Mi