labels:
  istio-injection: "enabled"
service:
  allocateLoadBalancerNodePorts: "true"
  annotations: 
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "${certificate_arn}"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
    service.beta.kubernetes.io/load-balancer-source-ranges: "${cidr_range}"
#    service.beta.kubernetes.io/aws-load-balancer-healthcheck-port: "31036"
