FROM apache/airflow:2.8.3

COPY dags/ /opt/airflow/dags/
#COPY entrypoint.sh /opt/airflow/entrypoint.sh
#
#USER 0
#RUN chown 50000:0 /opt/airflow/entrypoint.sh
#RUN chmod 777 /opt/airflow/entrypoint.sh
#USER 50000
#
#ENTRYPOINT ["/opt/airflow/entrypoint.sh"]
