images:
  airflow:
    repository: "${ecr_repo}"
    tag: "${docker_tag}"
    pullPolicy: Always
    
ingress:
  # Enable all ingress resources (deprecated - use ingress.web.enabled and ingress.flower.enabled)
  enabled: false
  web:
    # Enable web ingress resource
    enabled: false
  flower:
    # Enable web ingress resource
    enabled: false

# Airflow executor
# One of: LocalExecutor, LocalKubernetesExecutor, CeleryExecutor, KubernetesExecutor, CeleryKubernetesExecutor
executor: "CeleryExecutor"

migrateDatabaseJob:
  enabled: true
  useHelmHooks: true

# Otherwise pass connection values in
data:
  metadataConnection: # in production, create a new Secret and configure the name at ".Values.data.metadataSecretName"
    user: postgres
    pass: postgres
    protocol: postgresql
    port: 5432
    db: postgres

postgresql: # TESTE ONLY temporary Pod
  enabled: true
  image:
    tag: "11"
  auth:
    enablePostgresUser: true
    postgresPassword: postgres
    username: postgres
    password: postgres

workers:
  labels:
    istio-injection: "enabled"
  persistence:
    # Enable persistent volumes
    enabled: true
    # Volume size for worker StatefulSet
    size: 100Gi
    # If using a custom storageClass, pass name ref to all statefulSets here
    storageClassName: gp3
  resources:
    requests:
      cpu: 150m
      memory: 500Mi
    limits:
      cpu: 150m
      memory: 750Mi
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: topology.kubernetes.io/zone
            operator: In
            values:
            - us-east-1c

scheduler:
  labels:
    istio-injection: "enabled"
  resources:
    requests:
      cpu: 150m
      memory: 500Mi
    limits:
      cpu: 350m
      memory: 500Mi
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: topology.kubernetes.io/zone
            operator: In
            values:
            - us-east-1c

webservice:
  labels:
    istio-injection: "enabled"
  resources:
    requests:
      cpu: 150m
      memory: 256Mi
    limits:
      cpu: 350m
      memory: 256Mi
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: topology.kubernetes.io/zone
            operator: In
            values:
            - us-east-1c

triggerer:
  labels:
    istio-injection: "enabled"
  resources:
    requests:
      cpu: 150m
      memory: 500Mi
    limits:
      cpu: 150m
      memory: 500Mi
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: topology.kubernetes.io/zone
            operator: In
            values:
            - us-east-1c